[platformio]
default_envs = esp32-s3-n16r8

; === ESP32-S3 WROOM N16R8 + CC1101 (montage direct) ===
[env:esp32-s3-n16r8]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
board_upload.flash_size = 16MB

upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_src_filter = +<*> -<.git/> -<.github/> -<data/> -<icons/> -<boards/>

build_flags = 
    -DBOARD_HAS_PSRAM=1
    -DCORE_DEBUG_LEVEL=1
    -I src

lib_deps = 
    LittleFS
    lsatan/SmartRC-CC1101-Driver-Lib@2.5.7
    bblanchon/ArduinoJson@6.21.3
    me-no-dev/AsyncTCP@1.1.1
    me-no-dev/ESPAsyncWebServer@^3.0.0
    knolleary/PubSubClient@2.8.0
    links2004/WebSockets@^2.4.0
    ESP32Async/AsyncTCP@^3.3.2

; === LilyGO T-Embed CC1101 ===
[env:t-embed-cc1101]
platform = espressif32@6.5.0
board = t-embed-cc1101
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
board_upload.flash_size = 16MB

upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_src_filter = +<*> -<.git/> -<.github/> -<data/> -<icons/> -<boards/>

build_flags = 
    -DT_EMBED_CC1101
    -DBOARD_HAS_PSRAM=1
    -DCORE_DEBUG_LEVEL=1
    -I src

lib_deps = 
    LittleFS
    lsatan/SmartRC-CC1101-Driver-Lib@2.5.7
    bblanchon/ArduinoJson@6.21.3
    me-no-dev/AsyncTCP@1.1.1
    me-no-dev/ESPAsyncWebServer@^3.0.0
    knolleary/PubSubClient@2.8.0
    links2004/WebSockets@^2.4.0
    ESP32Async/AsyncTCP@^3.3.2
